version: "3"
services:
  db:
    image: postgres:latest
    container_name: "db"
    restart: always
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=wp_lab
#      - POSTGRES_PASSWORD=lab3
#      - POSTGRES_DB=balloon-shop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    image: vuevska/devops-project:latest
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://balloon-store-db.postgres.database.azure.com:5432/balloon-shop
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

volumes:
  postgres-data: