apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-project-config
  namespace: devops-ns
data:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/balloon-shop'
  POSTGRES_USERNAME: 'wp_lab'
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-project-app-secret
  namespace: devops-ns
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bGFiMw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  namespace: devops-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  minReadySeconds: 25
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: vuevska/devops-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: devops-project-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: devops-project-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-project-app-secret
                  key: SPRING_DATASOURCE_PASSWORD
